### ISSUE TITLE
Criação do checklist de Onboarding

### ISSUE THREAD

**Issue by cyz** [WoMakersCode/onboarding-voluntarios#4]
Template de checklist para ser utilizado após a criação da área funcional

**Comment by cyz** [comment]
O processo de identificação de novos membros inicia após a submissão do formulário de inscrição. O processo para identificação de área e convite pode seguir o seguinte template:

- [ ] Primeiro contato via e-mail, disponibilizando contatos de chat e vídeo-conferência.
- [ ] Após os primeiros contatos e identificando a disponibilidade de fazer parte de um time funcional, é necessário realizar uma reunião geral com os membros para apresentações e também para compartilhar o que está sendo feito e como a área escolhida pelo novo membro pode contribuir, sob uma atmosfera acolhedora. Esta conexão simples importa para o sucesso a longo prazo.
- [ ] Enviar NDA.
- [ ] Adicionar a lista NDA.
- [ ] Apresentar documentação de workflow da área e certificar-se que o novo membro está confortável.
- [ ] Apresentar o código de conduta
- [ ] Não custa lembrar que é importante dizer o quanto estamos felizes por ter um novo membro na equipe! :)
- [ ] Estabelecer uma agenda de reuniões 1:1 para saber seus sentimentos sobre a comunidade e como podemos nos integrar cada vez mais. Marcos de 30, 60, 90 e 180 dias são bons indicadores de agenda e suporte.
